### ISSUE TITLE
TagPro Replay interference after update to version 3.2

### ISSUE THREAD

**Issue by pandapleupleu** [wilcooo/TagPro-RL#1]
Hi, since the update from last night this script interferes with the replay extension. It now downloads a file instead of saving it to the extension on the tagpro homepage. If I try to import the text file it says: "Validation error: Schema validation failed: data/chat/1 should match exactly one schema in oneOf." When I turn this script off, it works fine again. Any idea on how to fix this?

**Comment by wilcooo** [comment]
Thank you, found the bug. You can update to ~~3.3~~ **Edit: 3.4 (whoops)** on [Greasy Fork](https://greasyfork.org/scripts/370044) (or wait until it does automatically).
The culprit was the "Hide and/or shorten the most annoying system messages" feature, that changed some chat strings to `null`, which Replays can't handle if it happens to load after RL chat.
It's weird though that this bug hasn't flown up earlier, as this feature has been unchanged since v1
